id: IA1EE5242
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T11:15:39+00:00'
last_modified: '2022-06-07T10:27:07.260509+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5476
  title: མཛོད་ཀྱི་རྣམ་བཤད་ཆོས་མངོན་རྒྱ་མཚོའི་སྙིང་པོ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BB84:
      image_group_id: I1KG5481
      title: Volume 1 of mdzod kyi rnam bshad chos mngon rgya mtsho'i snying po
      total_pages: 394
      order: 1
      base_file: BB84.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
